# ── Dev profile (HTTP localhost) ──────────────────────────────────────────────
# Cookie tidak perlu Secure di lokal karena HTTP
server.servlet.session.cookie.same-site=Lax
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.max-age=86400
server.servlet.session.timeout=86400s
